locale                   : "en-US"
title                    : "Shakhboz Khasanov"
title_separator          : "-"
name                     : &name "Shakhboz Khasanov"
description              : &description "Ph.D. in Nuclear Technology and Applications"
url                      : https://khasanov.github.io
baseurl                  : "/khasanov.github.io"
repository               : "diyorbek3467/khasanov.github.io"

author:
  name             : "Shakhboz Khasanov"
  avatar           : "images/shakhboz.jpg"
  bio              : "Associate Professor | Nuclear Physicist"
  location         : "Samarkand, Uzbekistan"
  employer         : "Samarkand State University"
  email            : "shakhbozkhasanov93@gmail.com"
  orcid            : "https://orcid.org/0000-0001-6787-9492"
  scopus           : "https://www.scopus.com/authid/detail.uri?authorId=57224443023"
  researchgate     : "https://www.researchgate.net/profile/Shakhboz-Khasanov-2"
  googlescholar    : ""
  github           : ""
  linkedin         : ""
